# This is a basic workflow to help you deploy to a Salesforce environment
# Created by Adrian Ioana using bash scripting, sfdx-cli, sfpowerscripts, Node, GitHub Actions
# Last modified date 9th May 2022

# Prerequisites:
  # Add deployment tags in your repository and update the "env.TAG=" variable below
  # Add the environment variables defined below, in GitHub - Settings - Secrets - Actions - Repository secrets

name: Deploy-to-DEVINT

on:
  workflow_dispatch:
  push:
    branches: 
      - develop

env:
# Sets environment variable 
  TAG:        DEVINT/v                     # Environment specific; To be updated for each environment;
  CLIENTID:   ${{secrets.DEVINT_CLIENTID}} # Environment specific; To be updated for each environment;
  USERNAME:   ${{secrets.DEVINT_USERNAME}} # Environment specific; To be updated for each environment;
  TESTLEVEL:  ${{secrets.NOTESTRUN}}       # Environment specific; To be updated for each environment;
  URL:        ${{secrets.TEST_ORG_URL}}    # Environment specific; To be updated for each environment;
  SERVER_KEY: ${{secrets.SERVER_KEY}}      # No update required

# A workflow which firstly runs the static resource builder, followed by the deployment itself  
jobs:
  # staticResources:
  # # The deploy_scripts/Compiler.xml and deploy_scripts/minimalize.bat have to be updated
  # # with the new src path: e.g., D:\a\repositoryName\repositoryName\ instead of d:\a\1\s\ !
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2.3.4
  #     with:
  #       fetch-depth: 0
  #       ref: ${{ github.ref }}

  #   - name: Build static resources
  #     run: |
  #         echo "${PWD##*/}"
  #         ls
  #         cd deploy_scripts
  #         ant prepareStaticResourcesZip
  #         cd ..
  #         mkdir -force force-app/main/default/staticresources
  #         cp src/staticresources/*.resource* force-app/main/default/staticresources
  #         git config user.email "automated@process"
  #         git config user.name "Automated Process"
  #         git add force-app/main/default/staticresources
  #         git commit -m 'Commit the B2B built static resources'
  #         git push ${{secrets.REPOSITORY}}

  deploy:
    # needs: staticResources
    runs-on: ubuntu-latest
    # container: salesforce/salesforcedx:latest-rc-slim
    container: dxatscale/sfpowerscripts:release-feb22
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Deploy
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/deploy.sh"
          "${GITHUB_WORKSPACE}/.github/deploy.sh"

      # # - name: Retrieve the code coverage
      # #   run:
      # #     sfdx force:apex:test:run --codecoverage --resultformat human -u ${{secrets.DEVINT_USERNAME}}
      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     # Required mail server address:
      #     server_address: smtp.office365.com
      #     # Required mail server port:
      #     server_port: 587
      #     # Optional (recommended): mail server username:
      #     username: ${{secrets.MAIL_USERNAME}}
      #     # Optional (recommended) mail server password:
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     # Required mail subject:
      #     subject: ${{ github.ref }} pipeline status
      #     # Required recipients' addresses:
      #     to: mamatha.dhanoji@molsoncoors.com,adrian.ioana@molsoncoors.com
      #     # Required sender full name (address can be skipped):
      #     from: GITHUB Workflow # <user@example.com>
      #     # Optional whether this connection use TLS (default is true if server_port is 465)
      #     # secure: true
      #     # Optional plain body:
      #     body: Build job of ${{ github.ref }} pipeline completed successfully!
      #     # Optional HTML body read from file:
      #     # html_body: file://README.html
      #     # Optional carbon copy recipients:
      #     # cc: kyloren@example.com,leia@example.com
      #     # Optional blind carbon copy recipients:
      #     # bcc: r2d2@example.com,hansolo@example.com
      #     # Optional recipient of the email response:
      #     # reply_to: luke@example.com
      #     # Optional Message ID this message is replying to:
      #     # in_reply_to: <random-luke@example.com>
      #     # Optional unsigned/invalid certificates allowance:
      #     # ignore_cert: true
      #     # Optional converting Markdown to HTML (set content_type to text/html too):
      #     # convert_markdown: true
      #     # Optional attachments:
      #     # attachments: attachments.zip,git.diff,./dist/static/*.js
      #     # Optional priority: 'high', 'normal' (default) or 'low'
      #     # priority: low
