# ============================================================================================================
# ============================================================================================================
# This is a basic workflow to help you deploy to a Salesforce environment
# Created by Adrian Ioana using bash scripting, sfdx-cli, sfpowerscripts, Node, GitHub Actions
# Last modified date 10th May 2022

### Prerequisites:
 ## Add the environment variables defined below, in GitHub - Settings - Secrets - Actions - Repository secrets
 ## The deploy_scripts/Compiler.xml and deploy_scripts/minimalize.bat have to be updated
  # with the new src path: e.g., D:\a\repositoryName\repositoryName\ instead of d:\a\1\s\ !

### Variables
 ## TAG - Deployment tag attached to a commit
 ## CLIENTID - DevOps conneected app consumer key
 ## USERNAME - Target org username
 ## TESTLEVEL - Can have one of the following values
  # NOTESTRUN
  # RUNLOCALTESTS
  # RUNSPECIFIEDTESTS -r class1.method1,class1.method2,class2.method1,etc
 ## URL - Target org login URL; test.salesforce.com, login.salesforce.com or custom domain
  # TEST_ORG_URL - https://test.salesforce.com
  # PROD_ORG_URL - https://login.salesforce.com
  # CUSTOM_ORG_URL - to be defined based on your needs
 ## SERVER_KEY - Certificate value that identifies with the DevOps app digital certificate server.crt
 ## REPOSITORY - A combination of username, personal access token and repository URL
# ============================================================================================================
# ============================================================================================================


name: Deploy-to-DEVINT

on:
  workflow_dispatch:
  push:
    paths:
        - 'force-app/**'
        - 'destructiveChanges/**'
        - 'src/**'
        # - '!.github/**'
        - '!deploy_scripts/**'
    branches: 
      - develop

# A workflow which firstly runs the static resource builder, followed by the deployment itself  
jobs:
  deploy:
    env: # Sets environment variables 
      TAG:        DEVINT/v                     # Environment specific; To be updated for each environment;
      CLIENTID:   ${{secrets.DEVINT_CLIENTID}} # Environment specific; To be updated for each environment;
      USERNAME:   ${{secrets.DEVINT_USERNAME}} # Environment specific; To be updated for each environment;
      TESTLEVEL:  ${{secrets.NOTESTRUN}}       # Environment specific; To be updated for each environment;
      URL:        ${{secrets.TEST_ORG_URL}}    # Environment specific; To be updated for Production;
      SERVER_KEY: ${{secrets.SERVER_KEY}}      # No update required
      REPOSITORY: ${{secrets.REPOSITORY}}      # No update required
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
  
  pull-request: 
    runs-on: ubuntu-latest
    environment: 'UAT'
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "feature/ft_poc_pr_creation"  # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into feature/ft_poc_pr_creation" # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        # pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_reviewer: "adrianioana,dhanojimamatha"                         # Comma-separated list (no spaces)
        # pr_assignee: "wei,worker"                         # Comma-separated list (no spaces)
        # pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        # pr_milestone: "Milestone 1"                       # Milestone name
        # pr_draft: true                                    # Creates pull request as draft
        pr_allow_empty: true                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}         # Not required to be defined - automatically created
# ================================================================================
# ================================================================================
# sfpowerscripts  
# MIT License

# Copyright (c) 2020 Accenture

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ================================================================================
# ================================================================================