# This is a basic workflow to help you validate against a Salesforce environment
# Created by Adrian Ioana using bash scripting, sfdx-cli, sfpowerscripts, Node, GitHub Actions
# Last modified date 9th May 2022

# Prerequisites:
  # Add the environment variables defined below, in GitHub - Settings - Secrets - Actions - Repository secrets

name: Validate-PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - develop

env:
# Sets environment variable 
  TAG:        DEVINT/v                     # Environment specific; To be updated for each environment;
  CLIENTID:   ${{secrets.DEVINT_CLIENTID}} # Environment specific; To be updated for each environment;
  USERNAME:   ${{secrets.DEVINT_USERNAME}} # Environment specific; To be updated for each environment;
  TESTLEVEL:  ${{secrets.NOTESTRUN}}       # Environment specific; To be updated for each environment;
  URL:        ${{secrets.TEST_ORG_URL}}    # Environment specific; To be updated for each environment;
  SERVER_KEY: ${{secrets.SERVER_KEY}}      # No update required
  REPOSITORY: ${{secrets.REPOSITORY}}      # No update required

jobs:
  validate:
  # Skipping the Static Resource stage during the Pull request validation.
    runs-on: ubuntu-latest
    container: dxatscale/sfpowerscripts:release-feb22
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Validate
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/validate.sh"
          "${GITHUB_WORKSPACE}/.github/validate.sh"