# This is a basic workflow to help you deploy to a Salesforce environment

name: Validate-PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the specified branches
on:
  pull_request:
    branches:
      - develop
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ValidatePR:
    runs-on: ubuntu-latest
    container: dxatscale/sfpowerscripts:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # - name: 'Install sfdx-cli & delta plugins'
      #   run: |
      #     npm install sfdx-cli --global
      #     echo 'y' | npx sfdx plugins:install sfpowerkit

      - name: Delta package
        run: |
          git rev-parse --abbrev-ref HEAD
          LATEST_STABLE_TAG=`git tag -l TEST/v*  --sort=creatordate | tail -n1`
          echo The last stable tag is $LATEST_STABLE_TAG
          CURRENT_COMMIT_ID=`git rev-parse --verify HEAD`
          echo The current commit ID is $CURRENT_COMMIT_ID
          npx sfdx sfpowerkit:project:diff -t $CURRENT_COMMIT_ID -r $LATEST_STABLE_TAG -d delta -x

          mkdir -p delta/convertmdapi
          mkdir -p delta/force-app
          cp destructiveChanges/destructiveChangesPre.xml destructiveChanges/destructiveChangesPost.xml destructiveChanges/package.xml delta/convertmdapi/
          cd delta/
          sfdx force:source:convert -r force-app -d convertmdapi
          cd ..
          cd delta/convertmdapi
          echo =================================================================================
          echo =================== The structure of convertmdapi folder ========================  
          echo =================================================================================    
          ls -d $PWD/*
          cd ..
          cd ..

      - name: Validate against target org
        run: |
          echo 
          echo =================================================================================
          echo ========================== Destructive Changes Pre ============================== 
          echo =================================================================================
          cat delta/convertmdapi/destructiveChangesPre.xml
          echo
          echo =================================================================================
          echo ========================== Main Deployment Package ============================== 
          echo =================================================================================
          cat delta/convertmdapi/package.xml
          echo =================================================================================
          echo ========================== Destructive Changes Post ============================= 
          echo =================================================================================
          cat delta/convertmdapi/destructiveChangesPost.xml
          sfdx force:auth:jwt:grant --clientid ${{secrets.TESTsalesforceDevOrgClientId}} --jwtkeyfile .github/server.key --username ${{secrets.TESTsalesforceOrgUserName}} --instanceurl ${{secrets.prodOrgInstanceURL}}
          sfdx force:mdapi:deploy --checkonly -d delta/convertmdapi -l ${{secrets.testLevel}} -u ${{secrets.TESTsalesforceOrgUserName}} --ignorewarnings -w 60



