name: Create release candidate

on:
  workflow_dispatch:
  push:
    paths:
        - 'force-app/**'
        - 'destructiveChanges/**'
        - 'src/**'
        - '!.github/**'
        - '!deploy_scripts/**'
    branches: 
      - feature-rc/*

permissions: write-all

jobs:
  create-rc:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{github.ref_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          
      - name: Creating release candidate
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/release-candidate.sh"
          "${GITHUB_WORKSPACE}/.github/release-candidate.sh"
