# This is a basic workflow to help you deploy to a Salesforce environment

name: Test-email-action

on: 
  workflow_dispatch:
# A workflow which firstly runs the static resource builder, followed by the deployment itself  
jobs:
  SendEmail:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          # Required mail server address:
          server_address: smtp.office365.com
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: UAT Unit Test Results Summary
          # Required recipients' addresses:
          to: mamatha.dhanoji@molsoncoors.com,adrian.ioana@molsoncoors.com
          # Required sender full name (address can be skipped):
          from: GITHUB Workflow # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: false
          # Optional plain body:
          body: The unit test job from ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          #html_body: file://README.html
          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          #reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          #ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          #convert_markdown: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          #priority: low