# This is a basic workflow to help you deploy to a Salesforce environment

name: Run-unit-tests

on: [workflow_dispatch]

# A workflow which firstly runs the static resource builder, followed by the deployment itself  
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    container: dxatscale/sfpowerscripts:latest
    steps:
      - name: Checkout the source branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Run unit tests
        run: |
          ls
          ls -d $PWD/*
          sfdx force:auth:jwt:grant --clientid ${{secrets.BEERMATE_UAT_CLIENTID}} --jwtkeyfile ./.github/server.key --username ${{secrets.BEERMATE_UAT_USERNAME}} --instanceurl ${{secrets.testOrgInstanceURL}}
          sfdx force:apex:test:run --codecoverage --resultformat human -u ${{secrets.BEERMATE_UAT_USERNAME}}