# This is a basic workflow to help you deploy to a Salesforce environment
name: UAT-unit-tests

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '35 14 * * *'
  push:
    branches: 
      - develop

# A workflow which firstly runs the static resource builder, followed by the deployment itself  
jobs:
  unitTest:
    env: # Sets environment variables 
      CLIENTID:   ${{secrets.BEERMATE_UAT_CLIENTID}} # Environment specific; To be updated for each environment;
      USERNAME:   ${{secrets.BEERMATE_UAT_USERNAME}} # Environment specific; To be updated for each environment;
      TESTLEVEL:  ${{secrets.NOTESTRUN}}       # Environment specific; To be updated for each environment;
      URL:        ${{secrets.TEST_ORG_URL}}    # Environment specific; To be updated for Production;
      SERVER_KEY: ${{secrets.SERVER_KEY}}      # No update required

    runs-on: ubuntu-latest
    # container: salesforce/salesforcedx:latest-rc-slim
    steps:
      - name: Checkout the source branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Run tests
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/unit-test.sh"
          "${GITHUB_WORKSPACE}/.github/unit-test.sh"
      
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Unit Test Results Summary
          to: mamatha.dhanoji@molsoncoors.com,adrian.ioana@molsoncoors.com
          from: GITHUB Workflow # <user@example.com>
          body:
          The "${{github.GITHUB_WORKFLOW}}" nightly run has finished! 
          Please find the Unit Test Summary report attached.
          attachments: report.txt



