# ============================================================================================================
# ============================================================================================================
# This is a basic workflow to help you run unit tests in a Salesforce environment
# Created by Adrian Ioana using bash scripting, sfdx-cli, sfpowerscripts, Node, GitHub Actions
# Last modified date 18th May 2022

### Prerequisites:
 ## Add the environment variables defined below, in GitHub - Settings - Secrets - Actions - Repository secrets

### Variables
 ## CLIENTID - DevOps conneected app consumer key
 ## USERNAME - Target org username
 ## URL - Target org login URL; test.salesforce.com, login.salesforce.com or custom domain
  # TEST_ORG_URL - https://test.salesforce.com
  # PROD_ORG_URL - https://login.salesforce.com
  # CUSTOM_ORG_URL - to be defined based on your needs
 ## SERVER_KEY - Certificate value that identifies with the DevOps app digital certificate server.crt
 ## MAIL_USERNAME - Email address; used for pipeline reporting
 ## MAIL_PASSWORD - Email password; used for pipeline reporting
# ============================================================================================================
# ============================================================================================================

name: UAT-unit-tests

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '35 14 * * *'
  # push:
  #   branches: 
  #     - develop

jobs:
  unitTest:
    runs-on: ubuntu-latest
    environment: DEVINT
    env: # Sets environment variables 
      CLIENTID:   ${{secrets.CLIENTID}}              # Environment specific; To be updated for each environment;
      USERNAME:   ${{secrets.USERNAME}}              # Environment specific; To be updated for each environment;
      URL:        ${{secrets.TEST_ORG_URL}}          # Environment specific; To be updated for Production;
      SERVER_KEY: ${{secrets.SERVER_KEY}}            # No update required
    container: salesforce/salesforcedx:latest-rc-slim
    steps:
      - name: Checkout the source branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Run tests
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/unit-test.sh"
          "${GITHUB_WORKSPACE}/.github/unit-test.sh"
      
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Unit Test Results Summary
          to: mamatha.dhanoji@molsoncoors.com,adrian.ioana@molsoncoors.com
          from: GITHUB Workflow # <user@example.com>
          body: The ${{github.workflow}} nightly run has finished! Please find the Unit Test Summary report attached.
          attachments: report.txt


# ================================================================================
# ================================================================================
# sfpowerscripts  
# MIT License

# Copyright (c) 2020 Accenture

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ================================================================================
# ================================================================================
