# This is a basic workflow to help you deploy to a Salesforce environment

name: SPRING21-unit-tests

on:
  workflow_dispatch:

# A workflow which firstly runs the static resource builder, followed by the deployment itself  
jobs:
  UnitTest:
    runs-on: ubuntu-latest
#     container: dxatscale/sfpowerscripts:latest
    steps:
      - name: Checkout the source branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Run unit tests
        run: |
          npm install sfdx-cli --global
          sfdx force:auth:jwt:grant --clientid ${{secrets.TESTsalesforceDevOrgClientId}} --jwtkeyfile ./.github/server.key --username ${{secrets.TESTsalesforceOrgUserName}} --instanceurl ${{secrets.testOrgInstanceURL}}
          SFDX_MAX_QUERY_LIMIT=30000 sfdx force:apex:test:run --codecoverage --resultformat human -u ${{secrets.TESTsalesforceOrgUserName}}
          execution_id=`sfdx force:data:soql:query -q "SELECT AsyncApexJobId FROM ApexTestRunResult where Status='Completed' order by EndTime desc limit 1" -t -u ${{secrets.TESTsalesforceOrgUserName}}`
          execution_report=`echo "$execution_id" | grep ^707*`
          sfdx force:apex:test:report -i $execution_report -u ${{secrets.TESTsalesforceOrgUserName}} > report.txt
      
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          # Required mail server address:
          server_address: smtp.office365.com
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Unit Test Results Summary
          # Required recipients' addresses:
          to: mamatha.dhanoji@molsoncoors.com,adrian.ioana@molsooncoors.com
          # Required sender full name (address can be skipped):
          from: GITHUB Workflow # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          #secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          # ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          attachments: report.txt
          # Optional priority: 'high', 'normal' (default) or 'low'
          # priority: low
