# This is a basic workflow to help you deploy to a Salesforce environment

name: SPRING21-unit-tests

on:
  workflow_dispatch:

# A workflow which firstly runs the static resource builder, followed by the deployment itself  
jobs:
  UnitTest:
    runs-on: ubuntu-latest
#     container: dxatscale/sfpowerscripts:latest
    steps:
      - name: Checkout the source branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Run unit tests
        run: |
          npm install sfdx-cli --global
          sfdx force:auth:jwt:grant --clientid ${{secrets.TESTsalesforceDevOrgClientId}} --jwtkeyfile ./.github/server.key --username ${{secrets.TESTsalesforceOrgUserName}} --instanceurl ${{secrets.testOrgInstanceURL}}
          SFDX_MAX_QUERY_LIMIT=30000 sfdx force:apex:test:run --codecoverage --resultformat human -u ${{secrets.TESTsalesforceOrgUserName}}
